apiVersion: v1
kind: Pod
metadata:
  name: podclock2
spec:
  containers:
  - name: webserver
    image: httpd:latest
    volumeMounts:
      - mountPath: /usr/local/apache2/htdocs
        name: timevol      

  - name: clockclient
    image: alpine:latest
    command: ['/bin/sh','-c','while true ; do wget -qO- http://localhost/time.txt ; sleep 2 ; done']

  volumes:
  - name: timevol
    persistentVolumeClaim:
      claimName: pvc-clock