apiVersion: v1
kind: Service
metadata:
  name:  svc-dockerregistry
spec:
  selector:
    app: dockerregistry
  type: NodePort
  ports:
  - port:  5000
    protocol: TCP
    targetPort:  dockerreg-port