apiVersion: v1
kind: Pod
metadata:
  name: podclock2
  labels:
    app: clockapp
spec:
  containers:
  - name: webserver
    image: httpd:latest
    volumeMounts:
      - mountPath: /usr/local/apache2/htdocs
        name: timevol
    ports:
    - name: http 
      containerPort: 80
      protocol: TCP
    readinessProbe:
        httpGet:
          path: /time.txt
          port: 80
        initialDelaySeconds: 10
        timeoutSeconds: 2  
    livenessProbe:
      exec:
        command: 
        - cat
        - /tmp/health
      initialDelaySeconds: 30
      timeoutSeconds: 5    
                 

  volumes:
  - name: timevol
    persistentVolumeClaim:
      claimName: pvc-clock