apiVersion: v1
kind: Pod
metadata:
  name: podclock3
spec:
  containers:
  - name: clockclient
    image: alpine:latest
    command: ['/bin/sh','-c','while true ; do wget -qO- http://svc-httpclock/time.txt ; sleep 2 ; done']
