apiVersion: v1
kind: Pod
metadata:
  name: podclock2
  labels:
    app: clockapp
spec:
  containers:
  - name: webserver
    image: httpd:latest
    volumeMounts:
      - mountPath: /usr/local/apache2/htdocs
        name: timevol
    ports:
    - name: http 
      containerPort: 80
      protocol: TCP
                 

  volumes:
  - name: timevol
    persistentVolumeClaim:
      claimName: pvc-clock