apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nostress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-nostress
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50